In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

# Importing the DataSet

In [18]:
dataset=pd.read_csv('Social_Network_Ads.csv') #load the dataset
X = dataset.iloc[:,:-1].values #independent variables
y = dataset.iloc[:,-1].values  #dependent variables

# Split train and test data

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.25)

# Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler  #feature scaling between the range -2 to 2
norm=StandardScaler()
X_train=norm.fit_transform(X_train)
X_test=norm.transform(X_test)
print(X_train)

[[ 1.99548387  2.15449477]
 [-0.9256864   1.5415379 ]
 [ 0.34015405  0.49075468]
 [ 0.04803702 -0.58921696]
 [-0.82831406 -0.67678223]
 [-1.12043109 -1.55243491]
 [ 0.82701576  0.5199431 ]
 [-0.73094172  1.89179897]
 [-0.82831406  0.14049361]
 [ 1.89811153 -1.2897391 ]
 [-0.14670766  1.62910317]
 [-0.24408001 -0.26814431]
 [-1.70466514  0.34481257]
 [ 0.43752639  0.2572473 ]
 [-1.80203749 -1.31892753]
 [-1.6072928  -0.06382535]
 [ 1.70336685  1.74585686]
 [ 0.34015405 -0.53084011]
 [-0.63356938 -1.61081175]
 [ 1.99548387  0.72426206]
 [ 0.24278171  0.14049361]
 [ 1.02176045 -1.17298541]
 [ 1.70336685 -0.91028961]
 [-0.73094172  1.33721894]
 [-0.04933532  1.95017581]
 [-1.89940983 -0.7643475 ]
 [ 0.04803702  0.28643572]
 [ 1.11913279  2.06692951]
 [-0.63356938  0.02373992]
 [-0.14670766 -0.47246327]
 [-0.24408001 -0.91028961]
 [ 0.14540936 -0.32652116]
 [ 0.34015405  0.05292834]
 [-0.14670766 -0.53084011]
 [ 0.04803702  1.22046525]
 [-1.6072928   0.5199431 ]
 [ 1.21650513 -0.99785488]
 

# Model Training

In [21]:
from sklearn.ensemble import RandomForestClassifier 
 # purity split and no of trees we want to build
classifier = RandomForestClassifier(n_estimators=10,criterion='entropy')
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

# Prediction

In [22]:
pred_val=[30,87000] #the age and salary pred values
print(classifier.predict(norm.transform([pred_val]))) #prediction

[0]


In [23]:
y_pred=classifier.predict(X_test)
print(y_pred) 
#comparing predict and test values of dependent variable
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[0 1 0 1 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 1 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 0 1 1 1 0]
[[0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]]


# Confusion Matrix

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
c_matrix=confusion_matrix(y_test,y_pred)  #confusion_matrix
print(c_matrix)
accuracy_score(y_test,y_pred)  #accuracy

[[62  1]
 [ 5 32]]


0.94

# Train Data Visualisation

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = norm.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(norm.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Random Forest Classification (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

# Test Data Visualisation

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = norm.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(norm.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Random Forest Classification (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()